#!/bin/bash
ls ./GiveLove/www/public/avatars >> deletedImage.txt
file="deletedImage.txt"
for image in $(cat $file)
do
	if [ "$image" == "default.jpg" ]
	then
		echo $image
	elif [ "$image" == "1702844204463LogoNRV.jfif" ]
	then
		echo $image
	else
		rm ./GiveLove/www/public/avatars/$image
	fi
done
rm deletedImage.txt
databases=$(curl -s http://admin:admin@127.0.0.1:5984/_all_dbs | sed 's/\[//;s/\]//;s/"//g')

IFS=',' read -ra db_list <<< "$databases"

for db in "${db_list[@]}"; do
  if [[ $db != gl* ]]; then
    echo "Deleting database: $db"
    curl -X DELETE http://admin:admin@127.0.0.1:5984/$db
  fi
done
db_url="http://admin:admin@127.0.0.1:5984"
db_name="gl_sessions"

all_docs=$(curl -s -X GET "$db_url/$db_name/_all_docs?include_docs=true")

doc_ids=$(echo "$all_docs" | grep -o '"id":"[^"]*' | sed 's/"id":"//')
doc_revs=$(echo "$all_docs" | grep -o '"rev":"[^"]*' | sed 's/"rev":"//')

IFS=$'\n'
i=0
for id in $doc_ids; do
  if [[ $id != "_design/getSession" ]]; then
    rev=$(echo "$all_docs" | grep -o "\"$id\",\"value\":{\"rev\":\"[^\"]*\"" | sed 's/.*"rev":"\([^"]*\)".*/\1/')
    
    if [[ -n $rev ]]; then
      echo "Deleting document: $id with rev: $rev"
      curl -s -X DELETE "$db_url/$db_name/$id?rev=$rev"
    else
      echo "Skipping document $id: No revision found"
    fi
  fi
done
db_url="http://admin:admin@127.0.0.1:5984"
db_name="gl_users"

all_docs=$(curl -s -X GET "$db_url/$db_name/_all_docs?include_docs=true")

doc_ids=$(echo "$all_docs" | grep -o '"id":"[^"]*' | sed 's/"id":"//')

IFS=$'\n'
for id in $doc_ids; do
  if [[ $id != *gl3_admin* && $id != *gl3_moderator* && $id != "_design/GetUsers" ]]; then
    rev=$(echo "$all_docs" | grep -o "\"$id\",\"value\":{\"rev\":\"[^\"]*\"" | sed 's/.*"rev":"\([^"]*\)".*/\1/')
    
    if [[ -n $rev ]]; then
      echo "Deleting document: $id with rev: $rev"
      curl -s -X DELETE "$db_url/$db_name/$id?rev=$rev"
    else
      echo "Skipping document $id: No revision found"
    fi
  else
    echo "Skipping protected document: $id"
  fi
done
