version: '3.1'

services:
 db:
  image: couchdb:latest
  volumes:
   - ./DataBase:/opt/couchdb/data
  ports:
   - "5984:5984"
  restart: always
  environment:
   - COUCHDB_USER=admin
   - COUCHDB_PASSWORD=admin
 node:
  build: ./www
  ports:
   - "3000:3000"
  restart: always
  volumes:
   - ./www:/www
  depends_on:
   - db
 
